config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users' }

  resources :pictures, only: [:index]
  resources :maps, only: [:index]
  resources :itineraries, only: [:index, :show]
  resources :shelf_spaces, only: [:index, :show]
  resources :extra_points, only: [:index, :show]
  resources :prices, only: [:index, :show]
  resources :msls, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :exports, only: [:index]
      resources :filters, only: [:index]
      resources :tables, only: [:index]

      post 'export/:name' => 'tables#export' , as: :export
      get 'verify_export' => 'tables#verify_export'
    end
  end

  root 'passthrough#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    managed_itineraries = []
    user.itineraries.each { |i| managed_itineraries << i.id }

    if user.role? :administrator
      can :manage, :all
    end

    if user.role? :coordenador
      can :manage, :ranking
      can :manage, :map
      can :manage, :picture
      can :manage, Itinerary, id: managed_itineraries
      can :manage, Picture, imageable_id: managed_itineraries, imageable_type: 'Itinerary'
    end

    if user.role? :unidade
      can :read, Itinerary, id: managed_itineraries
      cannot :index, Itinerary
    end

  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :itinerary

  validates_presence_of :question_id
  validates_presence_of :title
  validates_presence_of :itinerary_id
end

app/models/form.rb
class Form < ActiveRecord::Base
  has_many :questions
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :pictures
  belongs_to :itinerary
  has_many :answers
  has_many :item_features
end

app/models/item_feature.rb
class ItemFeature < ActiveRecord::Base
  belongs_to :item
  has_one :itinerary, :through => :item
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  acts_as_paranoid

  has_and_belongs_to_many :users
  has_many :pictures
  has_many :items
  has_many :item_features, through: :items
  has_many :answers
  has_many :scores
  has_many :points

  validates_presence_of :pos_tax_code
  validates_presence_of :visit_id
  validates_uniqueness_of :visit_id

  def gallery
    gallery = {}

    front = self.pictures.where(category: 'FACHADA').first
    gallery['front'] = front.nil? ? false : front.url

    extra_points = self.pictures
                       .joins("LEFT JOIN item_features ON item_features.item_id = pictures.item_id")
                       .joins("LEFT JOIN itineraries ON itineraries.id = pictures.itinerary_id")
                       .where("pictures.category = 'PONTO EXTRA'")
                       .pluck("DISTINCT ON (pictures.id) pictures.url, item_features.sku, itineraries.cycle")
    gallery['extra_points'] = extra_points.nil? ? false : extra_points.to_a

    gallery['gallery'] = self.pictures
                             .joins("LEFT JOIN item_features ON item_features.item_id = pictures.item_id")
                             .joins("LEFT JOIN itineraries ON itineraries.id = pictures.itinerary_id")
                             .where("pictures.category IN ('CONFINADA','PONTO PRINCIPAL','EXPOSIÇÃO')")
                             .pluck("DISTINCT ON (pictures.id) pictures.url, pictures.title, item_features.sku, itineraries.cycle")

    gallery
  end

  def msl
    hash = {}
    items = {}
    response = {}
    products = Msl.where(retail: retail).pluck(:cycle, :product)
    products.map do |cycle, product|
      hash[cycle] ||= []
      hash[cycle] << product
    end

    hash.each do |key, value|
      items[key] = ItemFeature.where(sku: value).where(manufacturer: 'RB').joins(:item)
                              .joins(:itinerary)
                              .where(itineraries: { cycle: key, store: store } )
                              .distinct.count(:sku)
    end

    items.each do |key, value|
      response[key] ||= 0
      response[key] = (items[key].to_f / hash[key].count.to_f).to_f
    end

    response.sort
  end

  def occurrence
    occurrence = self.answers.where(indication: 'OCORRÊNCIA').pluck(:title).first
    if occurrence == "OUTRA OCORRÊNCIA"
      return self.answers.where(indication: 'DESCRIÇÃO').pluck(:title).first
    else
      return occurrence
    end
  end
end

app/models/itinerary_meta.rb
class ItineraryMeta < ActiveRecord::Base
  self.table_name = "itinerary_meta"
  belongs_to :itinerary
end

app/models/job.rb
class Job < ActiveRecord::Base


	def self.get_link job_id

		job = Job.find_by(job_id: job_id)
		
		if !job.url.nil?
			return job.url
		else
			job.url = ""
			return 	job.url
		end	
				
	end	
end

app/models/kpi.rb
class Kpi < ActiveRecord::Base
  acts_as_paranoid

  validates_presence_of :name
  validates_presence_of :total_points
  has_many :questions
  has_many :superquestions, -> { where parent_id: nil }, class_name: 'Question'

  def self.total_percentage_count(value)
    total_points = Kpi.pluck('SUM(total_points)').first
    value = ((value.to_f / total_points) * 100).round(1)
    value.to_s + '%'
  end

  def total_points_by_itinerary(itinerary)
    Point.where(itinerary_id: itinerary.id,
                question_id: questions.map(&:id)
               ).sum(:value)
  end

  def gallery_by_itinerary_id(itinerary_id)
    Picture.where(indicator: name.parameterize(' ').upcase,
                  imageable_id: itinerary_id,
                  imageable_type: 'Itinerary'
                 )
  end

  def self.percentage_kpi(kpi, value)
    total_points = Kpi.where(name: kpi).pluck(:total_points).first
    value = ((value.to_f / total_points) * 100).round(1)
    value.to_s + '%'
  end

end

app/models/msl.rb
class Msl < ActiveRecord::Base
  # self.table_name = 'onetrade'
end

app/models/onetrade.rb
class Onetrade < ActiveRecord::Base
  self.table_name = 'onetrade'
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :itinerary
  belongs_to :item
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :itinerary
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :form
  has_many :answers

  validates_presence_of :title
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :roles_users
  belongs_to :resource, :polymorphic => true
  
  default_scope { order('name ASC') }
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :question

  validates_presence_of :question_id
  validates_presence_of :points
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :itinerary
  belongs_to :kpi

  validates_presence_of :itinerary_id
  validates_presence_of :kpi_id
end

app/models/spreadsheet.rb
class Spreadsheet < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_presence :file
  validates_attachment_content_type(
    :file,
    content_type: [
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'text/csv'
    ]
  )
  SOURCE_TYPES = {
    (RULES = 'rules') => 'Rules',
    (HIERARCHY = 'hierarchy') => 'Hierarchy'
  }
  scope :rules, -> { where(source_type: RULES) }
  scope :hierarchy, -> { where(source_type: HIERARCHY) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role

  validates_presence_of :name, :role_id

  has_and_belongs_to_many :itineraries

  default_scope { order('name ASC') }

  scope :coordinators, lambda {
    where('role_id = ?', 3)
  }


  def role?(role_sym)
    role.name.downcase.gsub(/( )/, '_').to_sym == role_sym
  end


  def name
    if self[:name] == "Administrador"
      'TRACKINGTRADE'
    else
      self[:name]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RECKITT BENCKISER</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="description" content="">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Aurora">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body class="dashboard">
    <div role="navigation" class="navbar navbar-fixed-top navbar-app">
      <div class="container-fluid">
        <div class="navbar-header">
          <button data-target="#main-menu" data-toggle="collapse" type="button" class="navbar-toggle collapsed"><span class="sr-only">Show/hide navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
          <button type="button" class="navbar-trigger sb-toggle-left"><span></span><span></span><span></span><span></span></button>
          <%= link_to root_url, class: "navbar-brand" do %>
            <img src="/assets/icn-310x310.png" alt="Reckitt">
          <% end %>
        </div>
        <div id="main-menu" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown"><a data-toggle="dropdown" href="#" aria-expanded="false" role="button" class="dropdown-toggle navbar-nav-user"><strong><%= current_user.try(:name) %></strong><span>online</span><i class="icon-arrow-down"></i></a>
              <ul role="menu" class="dropdown-menu">
                <li><li><%= link_to t("menu.logout"), destroy_user_session_path, :method => :delete %>  </li></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>

    <div class="sb-slidebar sb-left sb-style-push">
      <div class="aside aside-left">
        <div class="aside-section">

          <% if can? :index, :shelf_space %>
            <%= link_to shelf_spaces_path, class: 'aside-link' do %>
              <i class="icon-chart"></i>SHELF SPACE</a></a>
            <% end %>
          <% end %>

          <% if can? :index, :extra_points %>
            <%= link_to extra_points_path, class: 'aside-link' do %>
              <i class="icon-presence"></i>PONTO EXTRA</a></a>
            <% end %>
          <% end %>

          <% if can? :index, :prices %>
            <%= link_to prices_path, class: 'aside-link' do %>
              <i class="icon-price"></i>PREÇO</a></a>
            <% end %>
          <% end %>

          <% if can? :index, :msls %>
            <%= link_to msls_path, class: 'aside-link' do %>
              <i class="icon-mixe"></i>MSL</a></a>
            <% end %>
          <% end %>

          <% if can? :index, Itinerary %>
            <%= link_to itineraries_path, class: 'aside-link' do %>
              <i class="icon-sort"></i>LOJAS</a></a>
            <% end %>
          <% end %>

          <% if can? :index, :map %>
            <%= link_to maps_path, class: 'aside-link' do %>
              <i class="icon-local"></i>MAPA</a></a>
            <% end %>
          <% end %>

          <% if can? :index, :picture %>
            <%= link_to pictures_path, class: 'aside-link' do %>
              <i class="icon-picture"></i>GALERIA DE FOTOS</a></a>
            <% end %>
          <% end %>

        </div>
      </div>
    </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html ng-app="ReckittApp">
<head>
  <title>RECKITT BENCKISER</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="description" content="">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="Reckitt">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


<%= yield %>


</body>
</html>

app/views/partials/_filter_result.html.erb
<div id="collapse-tags" class="tags collapse">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="tags-inner">
          <!-- <h4 ng-if="!angular.equals({}, filters)"><%= t("graphs.filters.no_filter_selected")%></h4> -->
          <div class="tag-silo">
            <button ng-click="clearFilters()" type="button" class="tag">Limpar Filtros</button>
          </div>
          <div ng-repeat="value in filters.filter.itineraries.state_code.string" class="tag-silo">
            <button ng-click="removeFilter(filters, value)" type="button" class="tag">Estado: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.itineraries.city.string" class="tag-silo">
            <button ng-click="removeFilter('cities', value)" type="button" class="tag">Cidade: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.itineraries.store.string" class="tag-silo">
            <button ng-click="removeFilter('stores', value)" type="button" class="tag">Loja: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.itineraries.segment.string" class="tag-silo">
            <button ng-click="removeFilter('segments', value)" type="button" class="tag">Segmento: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.itineraries.economic_group.string" class="tag-silo">
            <button ng-click="removeFilter('economic_groups', value)" type="button" class="tag">Grupo: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.itineraries.retail.string" class="tag-silo">
            <button ng-click="removeFilter('retails', value)" type="button" class="tag">Rede: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.itineraries.area_manager.string" class="tag-silo">
            <button ng-click="removeFilter('area_managers', value)" type="button" class="tag">Gerente: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.item_features.category.string" class="tag-silo">
            <button ng-click="removeFilter('categories', value)" type="button" class="tag">Categoria: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.item_features.subcategory.string" class="tag-silo">
            <button ng-click="removeFilter('subcategories', value)" type="button" class="tag">Subcategoria: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.item_features.manufacturer.string" class="tag-silo">
            <button ng-click="removeFilter('manufacturers', value)" type="button" class="tag">Fabricante: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.item_features.brand_2.string" class="tag-silo">
            <button ng-click="removeFilter('brands', value)" type="button" class="tag">Marca: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
          <div ng-repeat="value in filters.filter.item_features.sku.string" class="tag-silo">
            <button ng-click="removeFilter('skus', value)" type="button" class="tag">SKU: {{value}}<!-- <i class="icon-close"></i> --></button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_lighthouse.html.erb
<div class="sub-navbar-kpis" ng-controller="FilterCtrl" >
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12">

          <div class="col-xs-1 col-lg-1">
          </div>

          <div class="col-xs-2 col-lg-2">
            <div class="box" id="door_box">
                <div class="box-head-lighthouse box-head">
                  <h3 class="box-title-lighthouse">ATENDIMENTO</h3>
                </div>
                <div class="box-body box-body-lighthouse">
                  <input checklist-change="toggleFilter()" type="checkbox" checklist-model="filters.filter.kpis.name.kpi_less_than_70_percent" value="ATENDIMENTO">
                  <i class="icon-line icon-atendimento red-icon"></i>
                </div>
            </div><!-- box-->
          </div>

          <div class="col-xs-2 col-lg-2">
            <div class="box" id="door_box">
                <div class="box-head-lighthouse box-head">
                  <h3 class="box-title-lighthouse">COMUNICAÇÃO VISUAL</h3>
                </div>
                <div class="box-body box-body-lighthouse">
                  <input checklist-change="toggleFilter()" type="checkbox" checklist-model="filters.filter.kpis.name.kpi_less_than_70_percent" value="COMUNICAÇÃO VISUAL">
                  <i class="icon-line icon-comunicacao_visual red-icon"></i>
                </div>
            </div><!-- box-->
          </div>

          <div class="col-xs-2 col-lg-2">
            <div class="box" id="door_box">
                <div class="box-head-lighthouse box-head">
                  <h3 class="box-title-lighthouse">INSTALAÇÕES</h3>
                </div>
                <div class="box-body box-body-lighthouse">
                  <input checklist-change="toggleFilter()" type="checkbox" checklist-model="filters.filter.kpis.name.kpi_less_than_70_percent" value="INSTALAÇÕES">
                  <i class="icon-line icon-manutencao red-icon"></i>
                </div>
            </div><!-- box-->
          </div>

          <div class="col-xs-2 col-lg-2">
            <div class="box" id="door_box">
                <div class="box-head-lighthouse box-head">
                  <h3 class="box-title-lighthouse">LIMPEZA</h3>
                </div>
                <div class="box-body box-body-lighthouse">
                  <input checklist-change="toggleFilter()" type="checkbox" checklist-model="filters.filter.kpis.name.kpi_less_than_70_percent" value="LIMPEZA">
                  <i class="icon-line icon-cleaner red-icon"></i>
                </div>
            </div><!-- box-->
          </div>


          <div class="col-xs-2 col-lg-2">
            <div class="box" id="door_box">
                <div class="box-head-lighthouse box-head">
                  <h3 class="box-title-lighthouse">PRODUTO</h3>
                </div>
                <div class="box-body box-body-lighthouse">
                  <input checklist-change="toggleFilter()" type="checkbox" checklist-model="filters.filter.kpis.name.kpi_less_than_70_percent" value="PRODUTO">
                  <i class="icon-line icon-medicine red-icon"></i>
                </div>
            </div><!-- box-->
          </div>

        </div>
      </div> <!-- row -->
    </div> <!-- container-fluid -->
  </div>  <!-- sub-navbar-kpis -->